[package]
authors = ["Maciej Dziardziel <fiedzia@gmail.com>"]
edition = "2018"
name = "dbexport"
version = "0.1.0"

[dependencies]
atty = "0.2.11"
chrono = "0.4.6"
csv = "1.0"
humantime = "1.2.0"
indicatif = "0.11.0"
prettytable-rs = "0.8.0"
structopt = "0.2"
termcolor = "1.0.4"
unicode-segmentation = "1.2.1"

[dependencies.mysql]
optional = true
version = "15"

[dependencies.spsheet]
optional = true
version = "0.1.0"
features = ["ods", "xlsx"]

[dependencies.postgres]
optional = true
version = "0.15.2"

[dependencies.sqlite]
optional = true
version = "0.24"

[features]
default = [
    "mysql",
    "spsheet",
    "postgres",
    "sqlite",
]
